<a href="https://colab.research.google.com/github/670510772/229351-Statlearningfordatasci1/blob/main/Lab08_670510772_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Statistical Learning for Data Science 2 (229352)
#### Instructor: Donlapark Ponnoprat

#### [Course website](https://donlapark.pages.dev/229352/)

## Lab #8

There are several deep learning frameworks in Python.

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/PyTorch_logo_black.svg/2560px-PyTorch_logo_black.svg.png" width="100"/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img src="https://upload.wikimedia.org/wikipedia/commons/2/2d/Tensorflow_logo.svg" width="40"/><img src="https://assets-global.website-files.com/621e749a546b7592125f38ed/62277da165ed192adba475fc_JAX.jpg" width="100"/>

In this Lab, we will use PyTorch

In [ ]:
import numpy as np

import torch

# Tensor basics

## Basic tensor creation

### Creating a scalar (1D) tensor

In [ ]:
a = torch.tensor(2)
a

tensor(2)

In [ ]:
b = torch.tensor(3)
a*b

tensor(6)

### Convert a tensor to scalar

In [ ]:
c = b.item()
c

3

### Creating 2D tensor

In [ ]:
A = torch.tensor([[1, 2], [5, 6]])
A

tensor([[1, 2],
        [5, 6]])

## Tensor and Numpy

### Convert from tensor to numpy array

In [ ]:
B = A.numpy()
B

array([[1, 2],
       [5, 6]])

### Convert from numpy array to tensor

In [ ]:
C = torch.from_numpy(B)

## PyTorch and GPU

check if GPU is available

In [ ]:
torch.cuda.is_available()

True

In [ ]:
C.device

device(type='cpu')

In [ ]:
D = C.cuda()
D

tensor([[1, 2],
        [5, 6]], device='cuda:0')

In [ ]:
E = D.cpu().numpy()
E

array([[1, 2],
       [5, 6]])

## Basic operations

In [ ]:
E*2

array([[ 2,  4],
       [10, 12]])

In [ ]:
D-2

tensor([[-1,  0],
        [ 3,  4]], device='cuda:0')

In [ ]:
D.cpu() * np.array([1, 2])

/tmp/ipython-input-4124694458.py:1: DeprecationWarning: __array_wrap__ must accept context and return_scalar arguments (positionally) in the future. (Deprecated NumPy 2.0)
  D.cpu() * np.array([1, 2])


tensor([[ 1,  4],
        [ 5, 12]])

### Matrix multiplication

In [ ]:
A = torch.tensor([[4, 5], [8, 9]])
B = torch.tensor([[1, 4], [7, 8]])
torch.matmul(A, B)

tensor([[ 39,  56],
        [ 71, 104]])

In [ ]:
torch.mm(A,B)

tensor([[ 39,  56],
        [ 71, 104]])

In [ ]:
A@B

tensor([[ 39,  56],
        [ 71, 104]])

### Matrix transpose

In [ ]:
A.t()

tensor([[4, 8],
        [5, 9]])

## Creating a specific type of tensor

In [ ]:
a = torch.zeros(1,2,3)
a

tensor([[[0., 0., 0.],
         [0., 0., 0.]]])

In [ ]:
b = torch.ones(1,2,3)
b

tensor([[[1., 1., 1.],
         [1., 1., 1.]]])

In [ ]:
I = torch.eye(3)
I

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [ ]:
R1 = torch.rand(2,3)
R1

tensor([[0.9250, 0.0316, 0.5911],
        [0.6030, 0.4773, 0.3541]])

In [ ]:
R2 = torch.randn(2,3)
R2

tensor([[-0.8282,  0.3908, -0.1470],
        [-0.2468,  0.1973,  0.7402]])

In [ ]:
a = torch.arange(6)
a

tensor([0, 1, 2, 3, 4, 5])

## Tensor's shape

In [ ]:
A.shape

torch.Size([2, 2])

In [ ]:
A.size()

torch.Size([2, 2])

### Checking the shape of a tensor

In [ ]:
u = torch.arange(6)
u.shape

torch.Size([6])

In [ ]:
v = u.reshape(2,3)
v

tensor([[0, 1, 2],
        [3, 4, 5]])

In [ ]:
w = u.view(3,2)
w

tensor([[0, 1],
        [2, 3],
        [4, 5]])

### Changing the shape of a tensor

In general, use `reshape`, but if you are worried about the memory usage, use `view`.

### Stacking and concatenating tensors

In [ ]:
a = torch.arange(4)
b = torch.arange(4) + 1
c = torch.stack([a, b], axis=0)

In [ ]:
d = torch.stack([a, b], axis=1)
d

tensor([[0, 1],
        [1, 2],
        [2, 3],
        [3, 4]])

In [ ]:
e = torch.cat([a, b], axis=0)
e

tensor([0, 1, 2, 3, 1, 2, 3, 4])

In [ ]:
f = torch.cat([a, b], axis=1)

IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

### Squeezing a tensor (removing an extra dimension)

In [ ]:
A = torch.zeros(1,2,3)
B = A.squeeze()
B

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
B.shape

torch.Size([2, 3])

### Unsqueezing a tensor (adding an extra dimension)

In [ ]:
# H.shape = (6, )
C = B.unsqueeze(axis=0)
C

tensor([[[0., 0., 0.],
         [0., 0., 0.]]])

In [ ]:
C.shape

torch.Size([1, 2, 3])

## Indexing

In [ ]:
P = torch.arange(12).reshape(3,4)
print(P)
print(P[0])
print(P[:, 0])
print(P[-1])
print(P[:, -1])
print(P[-2:])
print(P[:, -2:])

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([0, 1, 2, 3])
tensor([0, 4, 8])
tensor([ 8,  9, 10, 11])
tensor([ 3,  7, 11])
tensor([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[ 2,  3],
        [ 6,  7],
        [10, 11]])


In [ ]:
P[[0,1], [0,1]]
P[0:3, 0:3]

tensor([[ 0,  1,  2],
        [ 4,  5,  6],
        [ 8,  9, 10]])

In [ ]:
torch.inverse(torch.tensor([[2.0,0.0], [0.0,5.0]]))

tensor([[0.5000, 0.0000],
        [0.0000, 0.2000]])

# Exercise

In this exercise, we will simulate data to perform linear regression with 200 rows and 7 variables.

1. Create three random $N(0,1)$ tensors: `X`, `b` and `e` with `X.shape = (200, 7)`, `b.shape = (8, 1)` and `e.shape = (200, 1)` respectively.
2. Create a tensor that contains only 1's with shape `(200, 1)`.
3. Modify tensor `X` by adding the tensor in 2. as the first column.
4. Compute `y` using the following formula:
$$ y = Xb + e $$.
5. Fit a linear regression to the data `X` and `y` and obtain a tensor of estimated coefficient `b_hat`. The formula for `b_hat` is given by:
$$ \hat{b} = (X^TX)^{-1}X^Ty $$
Note: use `torch.inverse(...)` to calculate the inverse
6. Compute the predictions `y_hat`, given by:
$$ \hat{y} = X\hat{b} $$
7. Convert both `y` and `y_hat` from tensor to Numpy array and calculate MSE:
$$ MSE = \frac{1}{200}\sum_{i=1}^{200} (y_i - \hat{y}_i)^2 $$

In [ ]:
A**2

tensor([[[0., 0., 0.],
         [0., 0., 0.]]])

In [ ]:
A.sum()

tensor(0.)

In [ ]:
X = torch.tensor([[2, 3, 2], [4, 6, 7], [7, 2, 4]])
print(X)

X = torch.tensor([[1, 2, 3, 2], [1, 4, 6, 7], [1, 7, 2, 4]])
print(X)

tensor([[2, 3, 2],
        [4, 6, 7],
        [7, 2, 4]])
tensor([[1, 2, 3, 2],
        [1, 4, 6, 7],
        [1, 7, 2, 4]])


In [ ]:
X = torch.rand(200,7)
X

tensor([[0.9327, 0.0899, 0.5896,  ..., 0.0587, 0.4886, 0.7106],
        [0.5031, 0.7247, 0.7778,  ..., 0.5951, 0.9727, 0.8882],
        [0.1107, 0.6244, 0.1768,  ..., 0.9951, 0.4359, 0.9808],
        ...,
        [0.9766, 0.8437, 0.7028,  ..., 0.4024, 0.7078, 0.8915],
        [0.4071, 0.8139, 0.4763,  ..., 0.2675, 0.9077, 0.6567],
        [0.9089, 0.6167, 0.2862,  ..., 0.6727, 0.0365, 0.1248]])

In [ ]:
b = torch.rand(8,1)
b

tensor([[0.1334],
        [0.3230],
        [0.0766],
        [0.3157],
        [0.9576],
        [0.1945],
        [0.6343],
        [0.8618]])

In [ ]:
e = torch.rand(200,1)
e

tensor([[0.0070],
        [0.4841],
        [0.8078],
        [0.2598],
        [0.1679],
        [0.2071],
        [0.5127],
        [0.1067],
        [0.7937],
        [0.1520],
        [0.3928],
        [0.6724],
        [0.2045],
        [0.4645],
        [0.5743],
        [0.6215],
        [0.8674],
        [0.0338],
        [0.6701],
        [0.1647],
        [0.6847],
        [0.0684],
        [0.1330],
        [0.8199],
        [0.8424],
        [0.7417],
        [0.0372],
        [0.7521],
        [0.6732],
        [0.5896],
        [0.3248],
        [0.7630],
        [0.9372],
        [0.8024],
        [0.4329],
        [0.8665],
        [0.8321],
        [0.9581],
        [0.4409],
        [0.1349],
        [0.1711],
        [0.5479],
        [0.6439],
        [0.4389],
        [0.7474],
        [0.2072],
        [0.9011],
        [0.3121],
        [0.6186],
        [0.7646],
        [0.7611],
        [0.4514],
        [0.4609],
        [0.6080],
        [0.0309],
        [0

In [ ]:
o = torch.ones(200,1)
o

tensor([[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
      

In [ ]:
p = torch.cat([X, o], axis=1)
p

tensor([[0.9327, 0.0899, 0.5896,  ..., 0.4886, 0.7106, 1.0000],
        [0.5031, 0.7247, 0.7778,  ..., 0.9727, 0.8882, 1.0000],
        [0.1107, 0.6244, 0.1768,  ..., 0.4359, 0.9808, 1.0000],
        ...,
        [0.9766, 0.8437, 0.7028,  ..., 0.7078, 0.8915, 1.0000],
        [0.4071, 0.8139, 0.4763,  ..., 0.9077, 0.6567, 1.0000],
        [0.9089, 0.6167, 0.2862,  ..., 0.0365, 0.1248, 1.0000]])

In [ ]:
y = torch.matmul(p, b) + e
y

tensor([[1.7301],
        [3.3068],
        [3.6641],
        [2.3961],
        [2.1378],
        [2.2027],
        [2.2548],
        [2.9096],
        [2.6869],
        [2.5488],
        [1.9148],
        [3.4610],
        [1.6287],
        [3.1520],
        [2.5781],
        [2.9412],
        [3.3088],
        [2.4000],
        [2.4171],
        [2.0284],
        [2.7717],
        [1.6963],
        [2.2798],
        [2.5283],
        [2.6558],
        [2.8404],
        [2.8473],
        [3.1393],
        [2.9846],
        [3.4036],
        [2.3656],
        [3.3824],
        [3.1269],
        [2.8352],
        [2.5109],
        [3.0585],
        [2.9725],
        [3.2657],
        [2.2324],
        [2.4666],
        [2.8389],
        [2.0362],
        [2.0920],
        [3.0893],
        [2.8020],
        [2.7071],
        [2.7065],
        [2.7889],
        [2.4436],
        [3.2305],
        [3.3423],
        [2.8486],
        [2.7220],
        [2.4463],
        [2.3324],
        [1

In [ ]:
t = p.t() # Use p instead of X
u = torch.matmul(t, p) # Use p instead of X
v = torch.inverse(u)
w = torch.matmul(t, y)
z = v@w
z

tensor([[0.0834],
        [0.3736],
        [0.1411],
        [0.2677],
        [0.9287],
        [0.2022],
        [0.5308],
        [1.4222]])

In [ ]:
h = torch.matmul(X, z)
h

tensor([[1.9113],
        [3.9515],
        [3.2609],
        [2.5091],
        [2.2992],
        [2.2364],
        [1.7437],
        [3.2135],
        [2.2187],
        [3.1656],
        [1.6752],
        [3.3439],
        [1.2161],
        [3.2651],
        [2.0764],
        [2.9974],
        [3.0079],
        [2.6724],
        [2.1512],
        [2.3331],
        [2.3827],
        [1.7409],
        [2.5169],
        [1.5527],
        [2.4519],
        [2.3399],
        [3.4818],
        [2.5103],
        [2.8381],
        [3.6012],
        [2.4943],
        [3.6613],
        [2.6765],
        [2.6802],
        [2.3704],
        [2.3815],
        [2.5973],
        [2.6910],
        [1.8515],
        [2.8058],
        [3.5123],
        [1.4553],
        [1.5185],
        [3.4259],
        [2.9247],
        [2.8963],
        [1.9587],
        [3.1751],
        [2.1103],
        [3.1996],
        [3.1752],
        [3.1574],
        [3.0485],
        [2.1203],
        [3.2434],
        [1

In [ ]:
import numpy as np

y_hat = torch.matmul(p, z) # Use p for the augmented X and z for b_hat
y_np = y.detach().numpy()
y_hat_np = y_hat.detach().numpy()
mse = np.mean((y_np - y_hat_np)**2)
mse

np.float32(0.07939652)